# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 09:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryupload',
            name='zip_file',
            field=models.FileField(help_text='Select a .zip file of images to upload into a new Gallery.', upload_to='photologue/temp', verbose_name='images file (.zip)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='crop_from',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left'), ('center', 'Center (Default)')], default='center', max_length=10, verbose_name='crop from'),
        ),
        migrations.AlterField(
            model_name='photoeffect',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='The background color of the reflection gradient. Set this to match the background color of your page.', max_length=7, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='photoeffect',
            name='transpose_method',
            field=models.CharField(blank=True, choices=[('FLIP_LEFT_RIGHT', 'Flip left to right'), ('FLIP_TOP_BOTTOM', 'Flip top to bottom'), ('ROTATE_90', 'Rotate 90 degrees counter-clockwise'), ('ROTATE_270', 'Rotate 90 degrees clockwise'), ('ROTATE_180', 'Rotate 180 degrees')], max_length=15, verbose_name='rotate or flip'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='name',
            field=models.CharField(help_text='Photo size name should contain only letters, numbers and underscores. Examples: "thumbnail", "display", "small", "main_page_widget".', max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Use only plain lowercase letters (ASCII), numbers and underscores.', regex='^[a-z0-9_]+$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='watermark',
            name='image',
            field=models.ImageField(upload_to='photologue/watermarks', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='watermark',
            name='style',
            field=models.CharField(choices=[('tile', 'Tile'), ('scale', 'Scale')], default='scale', max_length=5, verbose_name='style'),
        ),
    ]
